services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: aprilio
      MYSQL_DATABASE: mydb
      MYSQL_USER: rangga
      MYSQL_PASSWORD: aprilio
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped
